language: generic
sudo: required
services:
	- docker
before_install:
	- docker build -t mayank74/react-test -f ./client/Dockerfile.dev ./client
        - echo "BEFORE INSTALL START"
        - gem install bundler
        - echo "BEFORE INSTALL END"
scripts:
	- docker run -e CI=true mayank74/react-test npm test -- --coverage
        - 'gem install bundler'
        - 'rake spec'
after_success:
	- docker build -t mayank74/multi-client ./client
	- docker build -t mayank74/multi-server ./server
	- docker build -t mayank74/multi-nginx ./nginx
	- docker build -t mayank74/multi-worker ./worker
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin  
        - docker push mayank74/multi-client
        - docker push mayank74/multi-client
        - docker push mayank74/multi-server 
        - docker push mayank74/multi-worker
